extends "res://tools/content_editor/ContentEditorRuntimeTuningSuite.gd"

const POST_EFFECT_DEFAULT_GROUP := "screen_shake"
const POST_EFFECT_GROUPS := [
	{
		"id": "screen_shake",
		"label": "Screen Shake",
		"description": "Normal and critical camera tremor generated by combat hits.",
		"search": "camera hit normal critical tremida shake",
		"fields": [
			"normal_shake_strength", "normal_shake_duration",
			"critical_shake_strength", "critical_shake_duration",
		],
	},
	{
		"id": "combat_feedback",
		"label": "Hit & Dash Feedback",
		"description": "Hit flashes, impact scale, floating numbers, smoke puffs and dash glints.",
		"search": "hit impact flash bump floating text smoke dash glint combat",
		"fields": [
			"smoke_puff_lifetime", "smoke_puff_scale",
			"floating_text_duration", "critical_text_duration",
			"hit_flash_duration", "critical_hit_flash_duration",
			"hit_bump_scale", "critical_bump_scale",
			"white_hit_flash_duration", "critical_white_hit_flash_duration",
			"dash_glint_count", "dash_glint_alpha", "dash_glint_lifetime", "dash_glint_spread",
		],
	},
	{
		"id": "world_occlusion",
		"label": "World Occlusion",
		"description": "Controls how tree canopies and roofs fade when they cover the player.",
		"search": "tree roof canopy transparency fade occlusion",
		"fields": [
			"world_occlusion_enabled", "world_occlusion_tree_alpha", "world_occlusion_roof_alpha",
			"world_occlusion_fade_speed", "world_occlusion_horizontal_ratio", "world_occlusion_vertical_ratio",
		],
	},
	{
		"id": "world_wind",
		"label": "Shared World Wind",
		"description": "One wind vector and gust rhythm shared by foliage and environmental motion.",
		"search": "wind foliage tree gust direction sway",
		"fields": [
			"tree_wind_strength", "tree_wind_speed",
			"world_wind_enabled", "world_wind_direction_x", "world_wind_direction_y",
			"world_wind_strength", "world_wind_gust_strength", "world_wind_gust_speed",
			"world_wind_large_scale", "world_wind_small_scale",
		],
	},
	{
		"id": "ambient_particles",
		"label": "Ambient Particles",
		"description": "World-anchored pollen, fireflies and leaves around the active gameplay region.",
		"search": "pollen polem firefly leaf leaves particles ambience",
		"fields": [
			"world_particles_enabled", "world_particles_pollen", "world_particles_fireflies",
			"world_particles_leaves", "world_particles_width", "world_particles_height",
			"world_particles_day_alpha", "world_particles_night_alpha",
			"world_particles_pollen_color", "world_particles_firefly_color", "world_particles_leaf_color",
		],
	},
	{
		"id": "selective_bloom",
		"label": "Selective Bloom",
		"description": "Extracts authored emissive pixels while suppressing neutral terrain and ordinary grass.",
		"search": "bloom glow emission emissive blur light",
		"fields": [
			"post_bloom_enabled", "post_selective_bloom", "post_bloom_threshold",
			"post_bloom_intensity", "post_bloom_mix", "post_blur_size",
			"post_blur_iterations", "post_blur_subdivisions", "post_colored_boost",
			"post_chroma_threshold", "post_luminance_threshold", "post_neutral_suppression",
			"post_warm_emissive_boost",
		],
	},
	{
		"id": "color_grading",
		"label": "Color Grading",
		"description": "Day and night tint, saturation, contrast, brightness and warm-light preservation.",
		"search": "color grading day night tint saturation contrast brightness shadows",
		"fields": [
			"post_grading_enabled", "post_day_tint", "post_night_tint",
			"post_day_saturation", "post_night_saturation",
			"post_day_contrast", "post_night_contrast",
			"post_day_brightness", "post_night_brightness",
			"post_warm_preservation", "post_shadow_lift", "post_cool_shadow_strength",
		],
	},
	{
		"id": "local_light_mask",
		"label": "Player Light Mask",
		"description": "Protects the area illuminated by the player from receiving the night filter a second time.",
		"search": "player local light night mask protection darkness lift",
		"fields": [
			"post_local_light_mask_enabled", "post_local_light_protection",
			"post_local_light_softness", "post_local_light_lift",
		],
	},
	{
		"id": "layered_fog",
		"label": "Layered World Fog",
		"description": "Broad mist, ground ribbons, middle-depth mist and distant haze in one pass.",
		"search": "fog mist haze ground depth atmosphere nevoa névoa",
		"fields": [
			"env_fog_enabled", "env_fog_color", "env_fog_density", "env_fog_coverage",
			"env_fog_softness", "env_fog_ground_density", "env_fog_ground_height",
			"env_fog_middle_density", "env_fog_depth_density", "env_fog_day", "env_fog_night",
		],
	},
	{
		"id": "light_shafts",
		"label": "Forest Light Shafts",
		"description": "World-anchored daylight beams rendered below the HUD.",
		"search": "forest light shafts beams sun rays god rays",
		"fields": [
			"env_shafts_enabled", "env_shafts_color", "env_shafts_intensity",
			"env_shafts_count", "env_shafts_width", "env_shafts_softness",
			"env_shafts_drift", "env_shafts_day", "env_shafts_night",
		],
	},
	{
		"id": "water_surface",
		"label": "Water Surface",
		"description": "Flow, ripples, reflection, caustics and authored top-down water colors.",
		"search": "water river lake pond stream ripple reflection caustic",
		"fields": [
			"env_water_enabled", "env_water_shallow", "env_water_deep", "env_water_highlight",
			"env_water_flow_speed", "env_water_ripple_scale", "env_water_ripple_strength",
			"env_water_reflection", "env_water_caustic",
		],
	},
	{
		"id": "micro_motion",
		"label": "Environmental Micro Motion",
		"description": "Subtle wind-linked rotation and breathing for flowers, fungi, herbs and small bushes.",
		"search": "micro motion flower fungus herb bush breathing sway animation",
		"fields": [
			"env_micro_enabled", "env_micro_rotation", "env_micro_plant_scale",
			"env_micro_flower_scale", "env_micro_fungus_scale",
			"env_micro_sway_speed", "env_micro_breathe_speed", "env_micro_wind",
		],
	},
]

var _selected_post_effect_group := POST_EFFECT_DEFAULT_GROUP


func _install_workspace_usability() -> void:
	if _runtime_shutting_down or not is_inside_tree():
		return
	super._install_workspace_usability()
	_install_recenter_editor_button()


func _install_recenter_editor_button() -> void:
	var toolbar := get_node_or_null("MarginContainer/MainLayout/ContentSplit/FormPanel/WorkspaceToolbar") as HBoxContainer
	if toolbar == null or toolbar.get_node_or_null("RecenterRuntimeEditor") != null:
		return
	var button := Button.new()
	button.name = "RecenterRuntimeEditor"
	button.text = "Recenter Editor"
	button.tooltip_text = "Bring the live Content Editor fully back inside the visible game window."
	button.pressed.connect(_recenter_runtime_editor)
	toolbar.add_child(button)
	var maximize_button := toolbar.get_node_or_null("EditorMaximizeToggle")
	if maximize_button != null:
		toolbar.move_child(button, maximize_button.get_index())


func _recenter_runtime_editor() -> void:
	var launcher := get_tree().get_first_node_in_group("runtime_content_editor_launcher")
	if launcher != null and launcher.has_method("recenter_runtime_editor"):
		launcher.call("recenter_runtime_editor")
		return
	var window := get_window()
	if window == null or not window.is_embedded():
		return
	var embedder := window.get_parent() as Window
	if embedder == null:
		return
	var available_size := Vector2i(embedder.get_visible_rect().size)
	if available_size.x <= 0 or available_size.y <= 0:
		available_size = embedder.size
	window.position = Vector2i(
		maxi(12, (available_size.x - window.size.x) / 2),
		maxi(40, (available_size.y - window.size.y) / 2)
	)


func _select_section(section: String, force := false) -> void:
	super._select_section(section, force)
	if section != SECTION_POST_EFFECTS or current_section != SECTION_POST_EFFECTS or current_record.is_empty():
		return
	if _post_effect_group(_selected_post_effect_group).is_empty():
		_selected_post_effect_group = POST_EFFECT_DEFAULT_GROUP
	current_id = _selected_post_effect_group
	current_original_id = "default"
	search_line_edit.placeholder_text = "Search effects: fog, bloom, particles, shake..."
	_refresh_record_list()
	_build_form_for_current_record()
	_update_action_buttons()


func _refresh_record_list() -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._refresh_record_list()
		return
	is_refreshing_list = true
	record_list.clear()
	var query := search_line_edit.text.strip_edges().to_lower()
	for group_value in POST_EFFECT_GROUPS:
		var group := group_value as Dictionary
		var group_id := str(group.get("id", ""))
		var label := str(group.get("label", group_id))
		var searchable := "%s %s %s %s" % [group_id, label, str(group.get("description", "")), str(group.get("search", ""))]
		if not query.is_empty() and not searchable.to_lower().contains(query):
			continue
		var index := record_list.item_count
		record_list.add_item(label)
		record_list.set_item_metadata(index, group_id)
		record_list.set_item_tooltip(index, str(group.get("description", "")))
		if group_id == _selected_post_effect_group:
			record_list.select(index)
	is_refreshing_list = false


func _on_record_selected(index: int) -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._on_record_selected(index)
		return
	if is_refreshing_list or index < 0 or index >= record_list.item_count:
		return
	var selected_id := str(record_list.get_item_metadata(index))
	if has_unsaved_changes and selected_id != _selected_post_effect_group:
		_set_status("Save or Revert before changing effect.", true)
		_refresh_record_list()
		return
	_select_post_effect_group(selected_id)


func _load_record(record_id: String) -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._load_record(record_id)
		return
	_select_post_effect_group(record_id)


func _select_post_effect_group(group_id: String) -> void:
	var group := _post_effect_group(group_id)
	if group.is_empty():
		group_id = POST_EFFECT_DEFAULT_GROUP
		group = _post_effect_group(group_id)
	_selected_post_effect_group = group_id
	current_id = group_id
	current_original_id = "default"
	current_record = data_store.get_record(ContentEditorData.SECTION_VFX_PROFILES, "default")
	has_unsaved_changes = false
	_build_form_for_current_record()
	_refresh_record_list()
	_update_action_buttons()
	_set_status("Selected %s" % str(group.get("label", group_id)))


func _build_post_effects_form() -> void:
	# Build the complete canonical form so all fields retain their values and the
	# existing serializer remains authoritative, then expose only the selected group.
	super._build_post_effects_form()
	var group := _post_effect_group(_selected_post_effect_group)
	if group.is_empty():
		group = _post_effect_group(POST_EFFECT_DEFAULT_GROUP)
		_selected_post_effect_group = POST_EFFECT_DEFAULT_GROUP

	for child in form_container.get_children():
		if child is CanvasItem:
			(child as CanvasItem).visible = false

	var shown_rows := 0
	var fields_value: Variant = group.get("fields", [])
	if fields_value is Array:
		for field_value in fields_value as Array:
			var control: Variant = field_controls.get(str(field_value))
			var top_level := _top_level_form_child(control)
			if top_level != null:
				top_level.visible = true
				shown_rows += 1

	var heading := Label.new()
	heading.name = "PostEffectGroupHeading"
	heading.text = str(group.get("label", "Post Effects"))
	form_container.add_child(heading)
	form_container.move_child(heading, 0)

	var note := Label.new()
	note.name = "PostEffectGroupDescription"
	note.text = str(group.get("description", ""))
	note.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	form_container.add_child(note)
	form_container.move_child(note, 1)

	var storage := Label.new()
	storage.name = "PostEffectStorageHint"
	storage.text = "Storage: data/vfx_profiles.json → default  •  Interface group: %s" % _selected_post_effect_group
	storage.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	form_container.add_child(storage)
	form_container.move_child(storage, 2)

	if shown_rows == 0:
		var warning := Label.new()
		warning.text = "No editable controls were found for this effect group."
		form_container.add_child(warning)
		form_container.move_child(warning, 3)

	form_title_label.text = "Post Effects: %s" % str(group.get("label", ""))
	current_file_label.text = "File: %s" % data_store.get_section_path(ContentEditorData.SECTION_VFX_PROFILES)


func _top_level_form_child(control_value: Variant) -> CanvasItem:
	if not control_value is Node or not is_instance_valid(control_value):
		return null
	var node := control_value as Node
	while node != null and node.get_parent() != form_container:
		node = node.get_parent()
	if node != null and node.get_parent() == form_container and node is CanvasItem:
		return node as CanvasItem
	return null


func _on_save_pressed() -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._on_save_pressed()
		return
	if _runtime_shutting_down:
		return
	var record := _get_post_effects_record()
	var error := data_store.validate_vfx_profile("default", "default", record)
	if not error.is_empty():
		_set_status(error, true)
		return
	data_store.set_record(ContentEditorData.SECTION_VFX_PROFILES, "default", "default", record)
	error = data_store.save_section(ContentEditorData.SECTION_VFX_PROFILES)
	if not error.is_empty():
		_set_status(error, true)
		return
	current_record = data_store.get_record(ContentEditorData.SECTION_VFX_PROFILES, "default")
	current_id = _selected_post_effect_group
	current_original_id = "default"
	has_unsaved_changes = false
	_refresh_record_list()
	_build_form_for_current_record()
	_update_action_buttons()
	call_deferred("_reload_runtime_content_after_save")
	_set_status("Saved %s and applied it to the running game." % str(_post_effect_group(_selected_post_effect_group).get("label", "Post Effects")))


func _on_revert_pressed() -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._on_revert_pressed()
		return
	current_record = data_store.get_record(ContentEditorData.SECTION_VFX_PROFILES, "default")
	has_unsaved_changes = false
	_build_form_for_current_record()
	_refresh_record_list()
	_update_action_buttons()
	_set_status("Reverted %s." % str(_post_effect_group(_selected_post_effect_group).get("label", "Post Effects")))


func _on_reload_current_pressed() -> void:
	if current_section != SECTION_POST_EFFECTS:
		super._on_reload_current_pressed()
		return
	var error := data_store.load_section(ContentEditorData.SECTION_VFX_PROFILES)
	if not error.is_empty():
		_set_status(error, true)
		return
	current_record = data_store.get_record(ContentEditorData.SECTION_VFX_PROFILES, "default")
	has_unsaved_changes = false
	_build_form_for_current_record()
	_refresh_record_list()
	_update_action_buttons()
	_set_status("Reloaded %s from disk." % str(_post_effect_group(_selected_post_effect_group).get("label", "Post Effects")))


func _post_effect_group(group_id: String) -> Dictionary:
	for group_value in POST_EFFECT_GROUPS:
		var group := group_value as Dictionary
		if str(group.get("id", "")) == group_id:
			return group
	return {}


func get_post_effect_group_ids() -> Array[String]:
	var ids: Array[String] = []
	for group_value in POST_EFFECT_GROUPS:
		ids.append(str((group_value as Dictionary).get("id", "")))
	return ids


func get_selected_post_effect_group() -> String:
	return _selected_post_effect_group
